name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        script_stop: true
        script: |
          cd cinzal/
          git checkout main
          git pull
          yarn install
          yarn build-server
          cd apps/server
          yarn db:push
          pm2 restart server